### Get all games
GET http://localhost:8000/games

### Get game by ID (replace :id with accurate user ID)

GET http://localhost:8000/games/656d50255b427c29c45466c1

### Post new game 

POST http://localhost:8000/games
Content-Type: application/json

{
    "title": "Game 3",
        "categories": [
            { "name": "Category A", "questions": ["A1", "A2", "A3", "A4"] },
            { "name": "Category B", "questions": ["B1", "B2", "B3", "B4"] },
            { "name": "Category C", "questions": ["C1", "C2", "C3", "C4"] },
            { "name": "Category D", "questions": ["D1", "D2", "D3", "D4"] },
            { "name": "Category E", "questions": ["E1", "E2", "E3", "E4"] },
            { "name": "Category F", "questions": ["F1", "F2", "F3", "F4"] }
        ],
    "img_url": "https://ibb.co/Gtx3h2k"
}

### Update existing game (replace :id with accurate user ID)
PUT http://localhost:8000/games/656d50255b427c29c45466c1
Content-Type: application/json

{
    "title": "Game e"
}

### Delete game (replace :id with accurate user ID)

DELETE http://localhost:8000/games/656d50255b427c29c45466c1

### Get users

GET http://localhost:8000/users

### Get user by ID (replace :id with accurate user ID)

GET http://localhost:8000/users/656d4fe35b427c29c45466af

### Get user by email (with middleware)

### Create new user

POST http://localhost:8000/users
Content-Type: application/json

{
    "firstName": "Juan",
    "lastName": "Perez",
    "email": "juanperez@gmail.com",
    "password": "iteso2023",
    "birthDate": "2000-1-1",
    "sex": "H",
    "role": "USER",
    "token": "WelcomeJeopardy",
    "access": "registrated"
}

### Edit user (replace :id with accurate user ID)

PUT http://localhost:8000/users/656d4fe35b427c29c45466af
Content-Type: application/json

{
    "token": "null" 
}

### Delete user (replace :id with accurate user ID)

DELETE http://localhost:8000/users/656d4fe35b427c29c45466af